### ISSUE TITLE
Angular 9 Support

### ISSUE THREAD

**Issue by hartjo** [d3lm/ngx-drag-to-select#107]
Hi do you have a working sample for angular 9 ivy?

**Comment by d3lm** [comment]
Hey there! Not yet but I plan to upgrade this soon. Wanna help out to get this over the finish line asap? I am a bit tight up with work right now so I would appreciate help.

**Comment by d3lm** [comment]
@hartjo Just wanted to get back to you and mention that this is done now. I only need to publish a new release. Will happen this week.

**Comment by sonicfran86** [comment]
@d3lm, I was migrating my project to angular 9 and the drag selection is not working with Ivy enabled. Looking forward for the new release :)

**Comment by d3lm** [comment]
@sonicfran86 Did you already try v4.0.0? I have released it yesterday.

**Comment by d3lm** [comment]
Closing this issue because the upgrade has been finished. See #110.
