### ISSUE TITLE
Any chances to run this with 'position: absolute' on the dtsSelectItem?

### ISSUE THREAD

**Issue by paulbijancoch** [d3lm/ngx-drag-to-select#108]
My dtsSelectItem needs to have an absolute position, and now the selection does not work. Any chances to get this going?

**Comment by d3lm** [comment]
Hey there! I am not sure, I'd have to take a look. Would you be able to take a stab at it and see if you can contribute with a PR? Is that something you can imagine to do? Would appreciate help if possible. Otherwise I can't promise anything soon but I see if I can take a quick look at it this weekend.

**Comment by paulbijancoch** [comment]
Hey @d3lm,
I already solved it in another way, but thank you for the offer, and sorry for the late reply.

**Comment by d3lm** [comment]
Hey! No worries @paulbijancoch. Do you mind sharing your solution? Curious to see how you solved it, just as a reference for users with a similar issue.

**Comment by paulbijancoch** [comment]
Hey @d3lm,

I figured out, that I need to get this working with a `transform: scale(' + $scale + ')'`. The general setup is a container, which holds a canvas, which lets to scrolling and zooming (panning) around the whole container.

So the boxInterecting does not work properly. I am working on a solution to scale the `dts-select-container` in sync.


I think to solution is very wide, and clumsy, so it might not be the best to integrate it in the FAQ. Nevermind, if you want to integrate the functionality of a panning/zooming background, I might do it with you ✌️

**Comment by d3lm** [comment]
Thanks for your update! I agree that this seems to be an edge case and if there are more people running into the same issue, we can come back and work out something together.
