### ISSUE TITLE
Angular 10 support

### ISSUE THREAD

**Issue by mindeltd** [d3lm/ngx-drag-to-select#109]
Currently I'm using Angular 9 and everything works just fine. After I update my project to Angular 10 I get an error message:

"ERROR in node_modules/ngx-drag-to-select/lib/drag-to-select.module.d.ts:5:59" - error TS2314: Generic type 'ModuleWithProviders<T>' requires 1 type argument(s).
5       static forRoot(config?: Partial<DragToSelectConfig>): ModuleWithProviders; "

It seems that "angular/core@10+" is using interface ModuleWithProviders which has a mandatory type parameter, so changing file's "ngx-drag-to-select/src/lib/drag-to-select.module.ts" line 24:
static forRoot(config: Partial<DragToSelectConfig> = {}): ModuleWithProviders {
to:
static forRoot(config: Partial<DragToSelectConfig> = {}): ModuleWithProviders'<'any'>' {
maybe would solve the issue.

**Comment by d3lm** [comment]
Hey! Thanks for the issue. Upgrading this library to Angular 10 (latest) is on my todo list and I am actually trying to do this this weekend. So I'd say hang in there a bit longer, and I ll try to upgrade it asap.

Thanks for the patience and using this library 🙏

**Comment by RahmatAliMalik5** [comment]
@d3lm Thanks Pal. I am also waiting the update for it.

**Comment by d3lm** [comment]
@RahmatAliMalik5 This is now being worked and will be released very soon. It's around the corner and likely being published this week. Watch out for a new release.

**Comment by d3lm** [comment]
This is not done (#110) and there's a new version 4.0.0 available on npm that now supports Angular >= 8.
