### ISSUE TITLE
Property dragOverItems is not released? 

### ISSUE THREAD

**Issue by sam-eah** [d3lm/ngx-drag-to-select#125]
Thanks again for the nice work, 
I can't seem to have the property `dragOverItems` working in my project, neither in the stack blitz live demo, despite habing everything up to date.  

It just seems to me that the latest feat was indeed merged in master, but there still hasn't been no release. Last release in date (4.0.0) is 6 months old.

Am I missing something?

**Comment by d3lm** [comment]
Oh yes, that's a good catch. I think I totally forgot to cut a new release. But I have just released `4.1.0` and updated the StackBlitz as well.

https://www.npmjs.com/package/ngx-drag-to-select
