### ISSUE TITLE
Selection lost on update if dtsSelectItem is assigned a value

### ISSUE THREAD

**Issue by lemmywrap** [d3lm/ngx-drag-to-select#139]
As far as I understand, I can either do:
`<mat-card [dtsSelectItem]>`
or the following:
`<mat-card [dtsSelectItem]="document.id">`

When using the latter however, I have noticed that when the items are updated, the selection is reset.

To reproduce, see the following [stackblitz](https://stackblitz.com/edit/ngx-drag-to-select-pe3w4v?file=src/app/app.component.html)

- In both containers, select Document 1
- Click the update items button
- Notice that the second selection will be cleared. 
- Afterwards it's also no longer possible to select Document 1 by dragging in the second select-container.

Problem is caused here, I think:
https://github.com/d3lm/ngx-drag-to-select/blob/4b12a79d381547ed3ca046d958cb4b1633d535f9/projects/ngx-drag-to-select/src/lib/select-container.component.ts#L347

`selectedItems` will be of type `number[]`, while `newList` is of type `SelectItemDirective[]`.

**Comment by d3lm** [comment]
Thanks for reporting this issue. I am not sure if I have the capacity to look into this right now. Would you be down to fix this and submit a PR?
