### ISSUE TITLE
SelectItemDirective.value unexpectedly returns this instead of dtsSelectItem when dtsSelectItem is falsy

### ISSUE THREAD

**Issue by Eagleseb** [d3lm/ngx-drag-to-select#160]
Minimal template to reproduce issue:

```html
<dts-select-container
  (selectedItemsChange)="selectItems($event)"
>
    <div
      [dtsSelectItem]="0"
    >
</div
</dts-select-container>
```

Selecting div item will call selectItems method with array [SelectItemDirective] instead of [0]. Same thing for any dstSelectItem with falsy value.
I think this is because internally, SelectItemDirective.value checks if dtsSelectItem is truthy. Instead it should check if dtsSelectItem !== undefined.

I can push a PR if you are interested.

Sorry if I'm not opening an issue correctly, first contribution here.

**Comment by d3lm** [comment]
Hey. Please provide a reproduction using stackblitz.com. I am pretty busy right now so I can't look into it and would appreciate a PR.

**Comment by Eagleseb** [comment]
Hello, thanks for your reply. Here's a fork of the project stackblitz putting the issue in evidence: https://stackblitz.com/edit/ngx-drag-to-select-7gyu4j?file=src/app/app.component.html

as you can see, with [dtsSelectItem]="document.id", selecting the document with id 0 (falsy) wrongly select the DTS directive instead of the id:
![image](https://user-images.githubusercontent.com/1732443/191497159-8776d1a0-eb62-4e46-8787-42ee19f2c31f.png)

I'll open a PR in a few days

**Comment by clickonben** [comment]
The current NPM version still has this bug in it.
