### ISSUE TITLE
Add unit and e2e tests

### ISSUE THREAD

**Issue by d3lm** [d3lm/ngx-drag-to-select#2]

**Comment by tdeschryver** [comment]
Did you have a specific framework in mind for the e2e tests?

**Comment by d3lm** [comment]
Yes, I wanted to use [Cypress](https://www.cypress.io/).

**Comment by tdeschryver** [comment]
I would like to help with this one 😄 

I would suggest to do this in two steps:
  1) setup cypress (and discuss the setup)
  2) create the tests

Would it also be better to wait till #16 is OK?

**Comment by d3lm** [comment]
Cool that you are super keen to help on this one too! Happy to see your contributions.

So I am wondering how far we get with e2e tests. It's difficult to test the different configurations, especially overriding the default configs. There's only one demo app and that app uses the defaults. I am wondering if it made more sense to test all that with unit tests. With a unit test you can create dedicated testing modules and test all the different options, features and what not. I mean with an e2e test we cannot really test whether the two-way data binding works, or test properties on the component instance. That's why I thought it would make more sense to only test some UI related things with e2e tests, like the default stylings and whether there's a selected class or not. But even then it's hard to test the case when we override the defaults.

What are your thoughts?

**Comment by d3lm** [comment]
And then, if we write more unit tests then e2e tests I was thinking if it made sense to use Cypress and to all the work to set it up and get rid of the protractor stuff.

> Would it also be better to wait till #16 is OK?

I don't think so, as the functionality should stay the same, even if it uses Angular v6.

**Comment by tdeschryver** [comment]
Yea you're completely right. I I just wanted to try out cypress 😅 
I haven't written a lot of angular tests, if you're OK with reviewing them I can add some incrementally.

**Comment by d3lm** [comment]
@tdeschryver For your information, I am already on it to write unit tests. If you want you can look into e2e tests with the default stack, meaning protractor. Please abstract things away using `PageObjects`.

**Comment by d3lm** [comment]
Ok, I started to write e2e tests now using Cypress.

**Comment by d3lm** [comment]
Tests have landed with 54c7ffae718767a0c9089b2f53e68e4110ad21ba.

@tdeschryver You can have a look and give feedback if you want.
