### ISSUE TITLE
Doesn't work with latest angular + CLI

### ISSUE THREAD

**Issue by SlimDogs** [d3lm/ngx-drag-to-select#20]
Throws errors related to RxJS... Can we expect any update soon?

**Comment by HarshaVardhanPVK** [comment]
Hi @d3lm, is there any update on support for Angular 6?

**Comment by d3lm** [comment]
Hey @HarshaVardhanPVK, yes there are a few bug fixes in the pipeline and once the PRs were merged I will take care of reviewing and merging the PR that upgrades the library to Angular v6. This will happen shortly within the next week or two probably.

**Comment by d3lm** [comment]
Just a quick status update here, I have took another look at the open PR and added a few comments there. Once those are addressed and the PR are merged, we'll continue with upgrading the library to Angular v6. Hang in there for a couple more days.

**Comment by HarshaVardhanPVK** [comment]
ok, thanq for update @d3lm

**Comment by jreijt** [comment]
Hi, any updates on Angular 6 support?

**Comment by timdeschryver** [comment]
@jreijt there is a PR open (#30). 
I think once this one lands, we'll be close to a release.

**Comment by d3lm** [comment]
Quick heads up, we are getting **really** close to a new major relaese. There are only two minor things left in #30, and once they are taken care of, we can merge the PR and cut a new release.

**Comment by d3lm** [comment]
I have created a [milestone](https://github.com/d3lm/ngx-drag-to-select/milestone/1) for the 2.0 release which will contain a few bug fixes and new features as well as the upgrade to Angular 6.

**Comment by d3lm** [comment]
Here's a PR (#33) that prepares the lib for a 2.0 release. The lib has already been upgraded to Angular 6, thanks to @timdeschryver 👏 Once this lands I'll cut the release and publish it on NPM. This means you guys can use the lib with the latest CLI and you benefit from bug fixes and new feature releases.

**Comment by d3lm** [comment]
ngx-drag-to-select 2.0.0 is now published and available on [NPM](https://www.npmjs.com/package/ngx-drag-to-select) 🎉. The StackBlitz was also updated, if you like to fiddle with it. It now uses Angular `^6.0.0` and ngx-drag-to-select `^2.0.0`.

As part of the release, I'll close this one. If you find any bugs or run into problems with the latest release, feel free to open an issue.
