### ISSUE TITLE
Update to Angular v6

### ISSUE THREAD

**Issue by d3lm** [d3lm/ngx-drag-to-select#3]

**Comment by tdeschryver** [comment]
Ok if I grab this one?

**Comment by tdeschryver** [comment]
Unfortunately I do not have have the experience of maintaining a 3rd party lib, so I'm not 100% sure of how to do this. To be honest I wanted to take a look at the code and thought this issue would be a win-win :smile: 

What about creating a branch (based of master) for bug fixes for Angular 5 and to use master for new features and the upgrade of Angular (and potentially bug fixes)?
Next time we can do the same if a new Angular version comes out.
I believe angular material does this?

**Comment by d3lm** [comment]
>What about creating a branch (based of master) for Angular 5 bug fixes and to use master for new features and the upgrade of Angular?

Yep, that's what I figured. But then I'd have to maintain two versions :smile: But I think this is the only way of upgrading the lib to v6.

> I believe Angular Material does this?

Yes, AFAIK Angular Material does it like that too. They use `master` as the most recent version and other branches for older versions. But please correct me if I am wrong.

**Comment by tdeschryver** [comment]
If I'm not mistaken I believe the NgRx team is looking into (or already setting up) their repo to handle multiple versions, fyi

**Comment by d3lm** [comment]
If you want you can look into upgrading the lib. Would love to see your PR! Good opportunity for you to go through the code. Let me know if you have any questions or encounter anything that can be improved. There's prolly a lot. I learned to do iterations and just get something out ASAP.

**Comment by d3lm** [comment]
So, it seems that some people still need the v5 version... so maybe we have to go with two versions after all.

**Comment by d3lm** [comment]
Now that tests have landed, do you mind do rebase your PR on the latest master? I also suggest to wait for this whole thing until Angular v6 has been released.

**Comment by tdeschryver** [comment]
No problemo, I was waiting for v6 like you suggested 😄

**Comment by d3lm** [comment]
This has landed with #30 🎉
