### ISSUE TITLE
Issues with webpack loading the library

### ISSUE THREAD

**Issue by chrisism** [d3lm/ngx-drag-to-select#31]
I am trying to use the library and I have added it to a feature module. I am using lazy loading, but this module is directly loaded. I am also using webpack (4) as my packager.

So I followed the guides and added the module import. Now when I start the webapp I get the following errors:
``
platform.es5.js:79 Uncaught TypeError: Object(...) is not a function
    at platform.es5.js:79
    at Object../node_modules/ngx-drag-to-select/esm5/ngx-drag-to-select.js (platform.es5.js:81)
    at __webpack_require__ (bootstrap:88)
    .....
``
What is happening here?

**Comment by chrisism** [comment]
Okay. Easy solution, it automatically got @angular/cdk v6 and we needed v5.
Fixed by getting correct version. 

Is there maybe an option we can do it without the hard cdk dependency?

**Comment by timdeschryver** [comment]
We've removed the CDK dependency in the latest version, but this version hasn't been released yet.
