### ISSUE TITLE
How to use it with Angular 5

### ISSUE THREAD

**Issue by Duogn** [d3lm/ngx-drag-to-select#34]
Hello I have a angular 5 project, how to use ngx-drag-to-select?

**Comment by timdeschryver** [comment]
Hi, you can install version 1.1.1 which supports Angular 5.
```cmd
npm install ngx-drag-to-select@1.1.1
```

**Comment by d3lm** [comment]
Exactly, you could install 1.1.1 as mentioned by @timdeschryver. However, I would suggest that you try to keep on the latest Angular version if possible. There is no separate branch for Angular 5 for this library and we will continue to support the latest Angular version and all other versions will unfortunately not receive bug fixes nor new features.

**Comment by Duogn** [comment]
Thanks

**Comment by d3lm** [comment]
You're welcome! Let me know if we can help you with anything or any issues you may encounter.
