### ISSUE TITLE
Square representing the selected area is not aligned with mouse when inside angular material mat-drawer

### ISSUE THREAD

**Issue by QuinntyneBrown** [d3lm/ngx-drag-to-select#4]
Square representing the selected area is not aligned with the actual mouse position when inside Angular Material `mat-drawer`.

Reproduction steps:

1. Open the following [StackBlitz](https://stackblitz.com/github/QuinntyneBrown/ngx-drag-to-select-getting-started-cli)

2. Navigate to the dashboard page

3. Select a group of documents

The selection rectangle is pretty far off from the actual mouse position.

**Expected Behavior**
Rectangle should be close to the mouse position.

**Comment by d3lm** [comment]
This should be fixed with the latest release `1.0.3`. Can you please verify if it works?
