### ISSUE TITLE
[BUG] Clicking on an item doesn't select it

### ISSUE THREAD

**Issue by shyamal890** [d3lm/ngx-drag-to-select#67]
https://stackblitz.com/edit/ngx-drag-to-select-errors?file=src/app/app.component.ts

- With `[selectOnDrag]="false"` click not selecting the items sometimes.

- From `Home` page go to `About` page and click on an item. If you try it a few times and look carefully, you would find that the drag box becomes visible for a short time over the 1st item.

**Comment by d3lm** [comment]
Do you want to take a look at this? I would appreciate help 👍 So maybe you can clone the repo, run it locally and try to find the cause for this bug.

**Comment by d3lm** [comment]
This is fixed in 3.1.1 which is now available on [npm](https://www.npmjs.com/package/ngx-drag-to-select).

**Comment by shyamal890** [comment]
@d3lm I am still facing the 2nd issue that is multiple elements being selected on view change. But unfortunately I am not able to reproduce the same in the demo. Would you like to have a look over anydesk.com ?

**Comment by d3lm** [comment]
Well, I need a reproducable anyways in order to find the cause of this issue if it's related to the lib. So I'd prefer if you could reproduce this.

**Comment by shyamal890** [comment]
Sometimes the library wrongly multi-selects items even though only one item is clicked. Check the gif attached.

Am unable to reproduce the issue on stackblitz. 

![selection issue](https://user-images.githubusercontent.com/6606965/51051271-55adbc00-15f9-11e9-9f63-4595e0b9d2ba.gif)
