### ISSUE TITLE
Is there a way to programatically enable/disable an element as selectable?

### ISSUE THREAD

**Issue by toddhd** [d3lm/ngx-drag-to-select#71]
Just to be clear, I'm not asking about changing something from selected to not selected and back again. Rather, I want to make specific element selectable/not selectable via code.

According to the docs, you make a DOM element "Selectable" by wrapping all the items you want to be selectable in a "<dts-select-container>" element, and then you also need to add the [dtsSelectItem]="item" tag to the element(s) in question. 

What I'd like to do is select some elements, and then make them un-selectable again via code. How can I achieve this?

I'm curious how the tagging works... for example, if I remote the "dts-select-item" class from the element, will that be enough to make it "not selectable"? Or is there a better way of doing this that won't break ngx-drag-to-select?"

**Comment by d3lm** [comment]
Do you mean you want to programatically select or deselect items? Or do you want to disable some elements so that the user cannot select them at all?

**Comment by ckapatch** [comment]
Hello, thank you for the great library, I have a similar question and yes want to know if you can mark an item as not selectable? So that if you attempt to select it will not allow it.

**Comment by d3lm** [comment]
Currently this is not supported. But I am more than happy to help you out if you sent a PR. But first, we should discuss the solution here, to make the process of the PR as smooth as possible.

**Comment by ckapatch** [comment]
Thanks @d3lm I was hoping to be able to somehow mark an item as not selectable, I'm not exactly sure of the best way to accomplish this but in theory it may look something like this:

```
<dts-select-container>
  <ul>
    <li [dtsSelectItem]="document" [dtsSelectable]="document.canSelect" #item *ngFor="let document of documents" >
      {{ document.name }}
      <i class="fa fa-check" *ngIf="item.selected"></i>
    </li>
  </ul>
</dts-select-container>
```
Would something like this be possible?

**Comment by d3lm** [comment]
Yea, indeed. This is what I was thinking too. We could add an input to the item itself that indicates if an item is selectable or not.
