### ISSUE TITLE
[Question] Do not allow selecting items dragging over items

### ISSUE THREAD

**Issue by jugonzalez40** [d3lm/ngx-drag-to-select#76]
Hi, great API.

There is any feature or any way to don't allow selecting items by dragging over itmes, but inside container (outside items).

i.e
You could only select from the red section, 
![image](https://user-images.githubusercontent.com/36463583/54831373-39c53700-4c88-11e9-9638-1e25f4d0156d.png)

**Comment by d3lm** [comment]
Hey @jugonzalez40, thank you for your feedback and your feature request / idea.

Currently this library does not support this but I am open for ideas and PRs! This should be fairly easy to implement. We basically have to introduce another configuration flag that only allows you to start the selection if the cursor is outside of the items' bounding box.

@timdeschryver What do you think? Do you think this is a too specific use case or do you think this should be implemented as well? I mean on Windows you can't basically start selecting on items. If you try this, you'd drag the item and not draw a selection box.

**Comment by timdeschryver** [comment]
I think this is a valid use case to add.

For now until this gets merged, I think this would be possible with css?
If it is, would it be enough to add it as a FAQ in the README?

```css
 pointer-events: none;
```

**Comment by d3lm** [comment]
@timdeschryver Absolutely. For now this can be solved with CSS and even for the real implementation we could also go for a CSS-based solution. So enabling a flag will add a class which sets the pointer events to `none` too. Or we would really disable the creation of the selection box if you start on an item.

**Comment by timdeschryver** [comment]
I think it would be better to add this with some RxJS because we handle all the behavior already with it. But I'm not against it to solve this with css tho 😄

**Comment by dariusll** [comment]
+1.  I need to use this library together with https://www.npmjs.com/package/ng-drag-drop , but when I  drag item to drop, also drag-to-select works. Implementing feature mentioned in this ticket would resolve my problem.

**Comment by d3lm** [comment]
Yep that sounds reasonable. Anybody wants to take a stab at implementing this? I'd really appreciate a PR.

**Comment by johny-gog** [comment]
+1 we'd love to see this too. :)
