### ISSUE TITLE
Selection rectangle not relative to scrollHeight

### ISSUE THREAD

**Issue by reppners** [d3lm/ngx-drag-to-select#8]
Had a little fun poking around with your lib and I think its awesome!

Theres only one thing that did not behave as I would've expected:
When a selection container is scrollable and a selection is started the browser starts scrolling when getting close to the edge of the viewport. My expectation was that the starting point of the selection rectangle "sticks" to it's coordinates on the scrollable content. The result being that the selection rectangle grows in size as scrolling happens, selecting more items in the process.

But it's relative to the viewport so scrolling while selecting will deselect items as they move out of the selection rectangle.

![drag-to-select-screencap](https://user-images.githubusercontent.com/3855704/38294219-6cdc5ff0-37ea-11e8-92c2-74321e1a8aef.gif)

**Comment by d3lm** [comment]
Hey there! Thanks, glad you like the library. 

It's indeed a bug and I appreciate that you have been fiddling with it. I'll fix it ASAP.
Thanks for reporting the issue.

**Comment by d3lm** [comment]
@reppners This should now be fixed. Also, the `select-container` can now be scrollable as well. This wasn't possible before. After the refactoring and rework of the positioning of the select box this should now be possible.

Travis is green and the code is deployed to [GitHub Pages](https://d3lm.github.io/ngx-drag-to-select/). Can you verify that it works as expected?

Note: It's not yet published to npm tho. I first wanna make sure it's working as expected.

**Comment by reppners** [comment]
Thanks for your effort :)

It's close, but Safari does not yet wanna play. I recorded it because its hard to describe in detail.

Safari 11.1
![drag-to-select-screencap-safari11_1](https://user-images.githubusercontent.com/3855704/38357972-5a06c5de-38c4-11e8-8921-f9c6871e459a.gif)

Chrome 65
![drag-to-select-screencap_chrome65](https://user-images.githubusercontent.com/3855704/38357908-245cee0e-38c4-11e8-88c4-f9279d0825ea.gif)

Firefox 59.0.2
![drag-to-select-screencap_firefox59_02](https://user-images.githubusercontent.com/3855704/38357909-2479e126-38c4-11e8-9c12-2c8a43d2d468.gif)

I noticed only Safari does actually automatically scroll when closing in on viewport edge. Chrome and Firefox must be scrolled manually while dragging. The selection rectangle does not update on scroll immediately.

**Comment by d3lm** [comment]
Ok so in Chrome and Firefox, both latest, it works for me. I have to investigate why the selection box is so much off in Safari. Is it the screen recording or why does it lag so much for you? For me it's quite smooth and also performance audits and recordings show that the FPS are relatively high, on average 59 FPS.

Scrolling when you come close to the viewport is a feature that must be implemented. I mainly focused on fixing the bug that the selection box stays where it is.

**Comment by reppners** [comment]
> Is it the screen recording or why does it lag so much for you?

Yes, it's just the recording. The only thing you can notice is, that on Chrome and Firefox the selection rectangle does not immediately follow the mouse pointer when scrolling. There's some event that makes it readjust to the mouse-pointer after scrolling but it I don't know what exactly triggers the readjust.

> Scrolling when you come close to the viewport is a feature that must be implemented. I mainly focused on fixing the bug that the selection box stays where it is.

Agree, it's a nice-to-have - I'd argue that how it behaves now regarding automatic scroll is expected behavior for users of each browser.

**Comment by d3lm** [comment]
> The only thing you can notice is, that on Chrome and Firefox the selection rectangle does not immediately follow the mouse pointer when scrolling.
Yes that is intentional. I am not listening for scroll events to update the selection box. That would probably have noticable impact on the performance but I am just guessing so. You have to move the mouse after scrolling. 

Not sure if you really want to scroll. After all, you have the keyboard shortcuts to add elements to the selection. But I get it that scrolling is convenient.

> I'd argue that how it behaves now regarding automatic scroll is expected behavior for users of each browser.
True. People are likely used to select and scroll at the same time. I may add this feature.

Thanks again for stress-testing my lib :smile:

**Comment by d3lm** [comment]
Just landed a fix for Safari. Can you verify that it works properly now across all browsers?

**Comment by reppners** [comment]
Works like a charm now! Thx for your effort :) 👍

**Comment by d3lm** [comment]
My pleasure! I'll cut a release and publish this on npm too.

**Comment by d3lm** [comment]
Fixed in [v1.0.5](https://www.npmjs.com/package/ngx-drag-to-select).
