### ISSUE TITLE
[Request] Publish master as a pre-release

### ISSUE THREAD

**Issue by zerefel** [d3lm/ngx-drag-to-select#91]
Hey everyone!

The last release of this package was about a year ago and a lot of new development has been added since then. Please consider publishing the current master branch as a pre-release or a release candidate.

Reasoning: It's harder to install the latest version from the GitHub repo since it requires `npm run build:lib` to get the `dist/` folder.

Cheers!

**Comment by d3lm** [comment]
Yes that totally makes sense and I agree with you. I ll publish an RC version. Thanks for bringing this up. Though, I think since the last published version the only new major feature is range selection. And that has landed a few weeks ago.

**Comment by d3lm** [comment]
There's now `3.2.0-rc.0` available on npm. You can get it by using the `next` tag, so to install the latest and greatest you can do `npm install ngx-drag-to-select@next`. You can find it on [npm](https://www.npmjs.com/package/ngx-drag-to-select).
